import { useEffect, lazy, Suspense } from "react";
import { useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { BookOpen } from "lucide-react";
import { useTheme } from "next-themes";
import { LanguageSelector } from "@/components/LanguageSelector";
import Footer from "@/components/Footer";
import { useSEO } from "@/hooks/useSEO";
import { useABTest } from "@/hooks/useABTest";
import { LandingHero } from "@/components/landing/LandingHero";

// Lazy load sections below the fold for better performance
const LandingBenefits = lazy(() => import("@/components/landing/LandingBenefits").then(m => ({ default: m.LandingBenefits })));
const LandingHowItWorks = lazy(() => import("@/components/landing/LandingHowItWorks").then(m => ({ default: m.LandingHowItWorks })));
const LandingLibrary = lazy(() => import("@/components/landing/LandingLibrary").then(m => ({ default: m.LandingLibrary })));
const LandingLanguages = lazy(() => import("@/components/landing/LandingLanguages").then(m => ({ default: m.LandingLanguages })));
const LandingTestimonials = lazy(() => import("@/components/landing/LandingTestimonials").then(m => ({ default: m.LandingTestimonials })));
const LandingPricing = lazy(() => import("@/components/landing/LandingPricing").then(m => ({ default: m.LandingPricing })));
const LandingFinalCTA = lazy(() => import("@/components/landing/LandingFinalCTA").then(m => ({ default: m.LandingFinalCTA })));

interface LandingProps {
  lang: "pt" | "es" | "en";
}

const Landing = ({ lang }: LandingProps) => {
  const navigate = useNavigate();
  const { t, i18n } = useTranslation();
  const { trackConversion } = useABTest();
  const { theme, setTheme } = useTheme();

  const seoConfigs = {
    pt: {
      title: "OnePageBook.ai - Aprenda qualquer livro em minutos com IA",
      description: "Obtenha resumos inteligentes com IA — grátis e em 3 idiomas. Economize horas e aprenda mais rápido. +5.000 resumos gerados por leitores em todo o mundo.",
      path: "/pt",
    },
    en: {
      title: "OnePageBook.ai - Learn any book in minutes with AI",
      description: "Get smart AI summaries — free and in 3 languages. Save hours and learn faster. +5,000 summaries generated by readers worldwide.",
      path: "/en",
    },
    es: {
      title: "OnePageBook.ai - Aprende cualquier libro en minutos con IA",
      description: "Obtén resúmenes inteligentes con IA — gratis y en 3 idiomas. Ahorra horas y aprende más rápido. +5.000 resúmenes generados por lectores en todo el mundo.",
      path: "/es",
    },
  };

  const config = seoConfigs[lang];
  useSEO({
    title: config.title,
    description: config.description,
    lang,
    path: config.path,
  });

  useEffect(() => {
    i18n.changeLanguage(lang);
    localStorage.setItem("language", lang);
  }, [lang, i18n]);

  // Force light theme on landing pages
  useEffect(() => {
    const previousTheme = theme;
    setTheme("light");
    
    return () => {
      if (previousTheme) {
        setTheme(previousTheme);
      }
    };
  }, []);

  const handleCTA = () => {
    trackConversion('cta_click');
    navigate(`/auth?lang=${lang}`);
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-50 w-full border-b border-border/40 bg-gradient-to-r from-background/95 via-background/50 to-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container mx-auto flex h-14 sm:h-16 items-center justify-between px-4 sm:px-6 lg:px-24">
          <div className="flex items-center gap-2">
            <BookOpen className="h-4 w-4 sm:h-5 sm:w-5 text-primary" />
            <span className="text-base sm:text-lg font-bold font-poppins bg-gradient-to-r from-primary to-purple-600 bg-clip-text text-transparent">OnePageBook</span>
          </div>
          <LanguageSelector />
        </div>
      </header>

      <LandingHero onCTA={handleCTA} />

      <Suspense fallback={
        <div className="min-h-[100px] flex items-center justify-center">
          <div className="w-6 h-6 border-2 border-primary border-t-transparent rounded-full animate-spin" />
        </div>
      }>
        <LandingBenefits />
        <LandingHowItWorks onCTA={handleCTA} />
        <LandingLanguages />
        <LandingTestimonials lang={lang} />
        <LandingPricing onCTA={handleCTA} />
        <LandingFinalCTA onCTA={handleCTA} />
      </Suspense>

      {/* Footer */}
      <footer className="border-t border-border bg-card py-8 sm:py-12">
        <div className="container mx-auto px-4 sm:px-6 lg:px-24">
          <div className="mb-6 flex items-center justify-center gap-2">
            <BookOpen className="h-6 w-6 text-primary" />
            <span className="text-lg font-bold font-poppins bg-gradient-to-r from-primary to-purple-600 bg-clip-text text-transparent">OnePageBook</span>
          </div>
          <p className="mb-6 text-center text-sm text-muted-foreground max-w-md mx-auto">
            {t("landing.footer.tagline")}
          </p>
          <Footer />
        </div>
      </footer>
    </div>
  );
};

export default Landing;
