import { useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ArrowLeft, BookOpen } from "lucide-react";
import { LanguageSelector } from "@/components/LanguageSelector";
import Footer from "@/components/Footer";

const Terms = () => {
  const { t, i18n } = useTranslation();
  const navigate = useNavigate();

  const content = {
    pt: {
      title: "Termos de Serviço",
      lastUpdated: "Última atualização: 02 de outubro de 2025",
      sections: [
        {
          title: "1. Aceitação dos Termos",
          content: "Ao acessar e usar o OnePageBook, você concorda em cumprir estes Termos de Serviço. Se você não concorda com qualquer parte destes termos, não deve usar nosso serviço."
        },
        {
          title: "2. Descrição do Serviço",
          content: "OnePageBook é uma plataforma que gera resumos práticos de livros em uma página. O serviço está disponível em https://onepagebook.ai e oferece planos gratuitos e premium."
        },
        {
          title: "3. Contas de Usuário",
          content: "Você é responsável por manter a confidencialidade de sua conta e senha. Você concorda em aceitar a responsabilidade por todas as atividades que ocorrem em sua conta."
        },
        {
          title: "4. Uso Aceitável",
          content: "Você concorda em usar o OnePageBook apenas para fins legais e de acordo com estes Termos. Você não deve usar o serviço de forma que possa danificar, desabilitar ou prejudicar o serviço."
        },
        {
          title: "5. Propriedade Intelectual",
          content: "O conteúdo gerado pelo OnePageBook é fornecido para uso pessoal. Todos os direitos, títulos e interesses no serviço permanecem com o OnePageBook."
        },
        {
          title: "6. Limitação de Responsabilidade",
          content: "O OnePageBook é fornecido 'como está'. Não garantimos que o serviço será ininterrupto ou livre de erros. Não seremos responsáveis por quaisquer danos indiretos, incidentais ou consequenciais."
        },
        {
          title: "7. Modificações dos Termos",
          content: "Reservamo-nos o direito de modificar estes termos a qualquer momento. Continuaremos a notificá-lo sobre mudanças materiais através do serviço ou por e-mail."
        },
        {
          title: "8. Contato",
          content: "Para dúvidas sobre estes Termos, entre em contato conosco em sac@onepagebook.ai"
        }
      ]
    },
    en: {
      title: "Terms of Service",
      lastUpdated: "Last updated: October 02, 2025",
      sections: [
        {
          title: "1. Acceptance of Terms",
          content: "By accessing and using OnePageBook, you agree to comply with these Terms of Service. If you do not agree with any part of these terms, you should not use our service."
        },
        {
          title: "2. Service Description",
          content: "OnePageBook is a platform that generates practical book summaries in one page. The service is available at https://onepagebook.ai and offers free and premium plans."
        },
        {
          title: "3. User Accounts",
          content: "You are responsible for maintaining the confidentiality of your account and password. You agree to accept responsibility for all activities that occur under your account."
        },
        {
          title: "4. Acceptable Use",
          content: "You agree to use OnePageBook only for lawful purposes and in accordance with these Terms. You must not use the service in any way that could damage, disable, or impair the service."
        },
        {
          title: "5. Intellectual Property",
          content: "Content generated by OnePageBook is provided for personal use. All rights, titles, and interests in the service remain with OnePageBook."
        },
        {
          title: "6. Limitation of Liability",
          content: "OnePageBook is provided 'as is'. We do not guarantee that the service will be uninterrupted or error-free. We shall not be liable for any indirect, incidental, or consequential damages."
        },
        {
          title: "7. Modifications to Terms",
          content: "We reserve the right to modify these terms at any time. We will continue to notify you of material changes through the service or by email."
        },
        {
          title: "8. Contact",
          content: "For questions about these Terms, contact us at sac@onepagebook.ai"
        }
      ]
    },
    es: {
      title: "Términos de Servicio",
      lastUpdated: "Última actualización: 02 de octubre de 2025",
      sections: [
        {
          title: "1. Aceptación de los Términos",
          content: "Al acceder y usar OnePageBook, usted acepta cumplir con estos Términos de Servicio. Si no está de acuerdo con alguna parte de estos términos, no debe usar nuestro servicio."
        },
        {
          title: "2. Descripción del Servicio",
          content: "OnePageBook es una plataforma que genera resúmenes prácticos de libros en una página. El servicio está disponible en https://onepagebook.ai y ofrece planes gratuitos y premium."
        },
        {
          title: "3. Cuentas de Usuario",
          content: "Usted es responsable de mantener la confidencialidad de su cuenta y contraseña. Usted acepta asumir la responsabilidad de todas las actividades que ocurran en su cuenta."
        },
        {
          title: "4. Uso Aceptable",
          content: "Usted acepta usar OnePageBook solo para fines legales y de acuerdo con estos Términos. No debe usar el servicio de ninguna manera que pueda dañar, deshabilitar o perjudicar el servicio."
        },
        {
          title: "5. Propiedad Intelectual",
          content: "El contenido generado por OnePageBook se proporciona para uso personal. Todos los derechos, títulos e intereses en el servicio permanecen con OnePageBook."
        },
        {
          title: "6. Limitación de Responsabilidad",
          content: "OnePageBook se proporciona 'tal cual'. No garantizamos que el servicio sea ininterrumpido o libre de errores. No seremos responsables de ningún daño indirecto, incidental o consecuente."
        },
        {
          title: "7. Modificaciones de los Términos",
          content: "Nos reservamos el derecho de modificar estos términos en cualquier momento. Continuaremos notificándole sobre cambios materiales a través del servicio o por correo electrónico."
        },
        {
          title: "8. Contacto",
          content: "Para preguntas sobre estos Términos, contáctenos en sac@onepagebook.ai"
        }
      ]
    }
  };

  const lang = i18n.language as keyof typeof content;
  const pageContent = content[lang] || content.pt;

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <header className="border-b border-border">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <Button variant="ghost" onClick={() => navigate("/")}>
            <ArrowLeft className="w-4 h-4 mr-2" />
            Home
          </Button>
          <LanguageSelector />
        </div>
      </header>

      <main className="container mx-auto px-4 py-8 max-w-4xl flex-1">
        <div className="flex justify-center mb-8">
          <div className="flex items-center gap-2">
            <BookOpen className="w-8 h-8 text-primary" />
            <h1 className="text-2xl font-bold text-foreground">OnePageBook</h1>
          </div>
        </div>
        <Card className="p-8">
          <h1 className="text-3xl font-bold mb-4">{pageContent.title}</h1>
          <p className="text-sm text-muted-foreground mb-8">{pageContent.lastUpdated}</p>
          
          <div className="space-y-6">
            {pageContent.sections.map((section, index) => (
              <section key={index}>
                <h2 className="text-xl font-semibold mb-3">{section.title}</h2>
                <p className="text-foreground leading-relaxed">{section.content}</p>
              </section>
            ))}
          </div>
        </Card>
      </main>

      <Footer />
    </div>
  );
};

export default Terms;
